# Generated by Django 4.0 on 2022-01-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, null=True)),
                ('service_category', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electronics', 'Electronics'), ('Household', 'Household')], max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
